name: Exemplo Input
run-name: Exemplo workflow para input, executado por ${{ github.actor }}
on:
    workflow_dispatch:
        inputs:
            versao: 
                type: string
                required: true
                default: dev
                description: "Versão da nova release"
            numero_card:
                type: number
                required: true
                description: "Número de card da tarefa desse commit"
            fazer_deploy:
                type: boolean
                required: true
                description: "Especifica se deve ou não fazer deploy"
            ambiente:
                type: choice
                required: true
                description: "Ambiente de Deploy"    
                options: 
                    - Desenvolvimento
                    - Homologação
                    - Produção  
    jobs:
        valores_input:
            runs-on: ubuntu-latest
            steps:
                - name: Exibindo o contexto de innput completo
                  run: echo ""{{ toJson(inputs) }} 
                - name: Exibindo os valores individualmente
                  run: |
                    echo "Esses são os valores passados nos inputs" 
                    echo "A versão é: ${{ inputs.versao}}                    
                    echo "O Card é: ${{ inputs.numero_card}}    
                    echo "Deve fazer deploy: ${{ inputs.fazer_deploy}}   
                    echo "O Ambiente é: ${{ inputs.ambiente}}                

