name: Exemplo Output
run-name: Exemplo workflow para output, executado por ${{ github.actor }}
on:
    workflow_dispatch:
jobs:
    gerando_output:
        runs-on: ubuntu-latest
        outputs:
          output-shell: ${{  steps.exemplo-output.action_random  }}
        steps:
            - name: Gerando output com shell
              id: exemplo-output
              run: |
                ACTION_RANDOM=$(( $RANDOM ))
                echo "action_random=$ACTION_RANDOM" >> $GITHUB_OUTPUT
            - name: Exibindo o output da action exemplo output
              run: echo  "${{ steps.exemplo-output.outputs.action_random}}"  
    exibindo-valores:
        needs: [gerando_output]
        runs-on: ubuntu-latest
        steps:
            - name: Exibindo os outputs do gerando_output
              run: |
                  echo "Output Shell: ${{ needs.gerando_output.outputs.output-shell }}"
                
    
                
